# Generated by Django 4.0.1 on 2022-02-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_cidade_cliente_cidadenatal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cidadeNatal',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.ManyToManyField(to='cliente.Cidade'),
        ),
    ]
