# Generated by Django 4.0.1 on 2022-02-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_remove_cliente_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
    ]
