# Generated by Django 4.0.1 on 2022-02-20 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_remove_cliente_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.cidade'),
            preserve_default=False,
        ),
    ]
