# Generated by Django 4.0.1 on 2022-03-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0025_alter_cliente_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='renda',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
