# Generated by Django 4.0.1 on 2022-03-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0026_alter_cliente_renda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='EstCivil',
            field=models.IntegerField(choices=[(1, 'Solteiro(a)'), (2, 'Casado(a)'), (3, 'Divorciado(a)'), (4, 'Viúvo(a)'), (5, 'Desquitado(a)'), (6, 'União Estável')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='carro',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='filhos',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
