# Generated by Django 4.0.1 on 2022-03-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0027_alter_cliente_estcivil_alter_cliente_carro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EstadoCivil',
            },
        ),
    ]
