# Generated by Django 4.0.1 on 2022-01-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelproduto',
            table='produto',
        ),
    ]
