# Generated by Django 4.0.1 on 2022-01-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_categoria_rename_modelproduto_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categ',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='produto.categoria'),
            preserve_default=False,
        ),
    ]
