# Generated by Django 4.0.1 on 2022-01-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_modelproduto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.RenameModel(
            old_name='ModelProduto',
            new_name='Produto',
        ),
    ]
