# Generated by Django 4.0.1 on 2022-02-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_table_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='categ',
        ),
    ]
